name = 'OSBFuelImport'
description = 'OSBFuelImport'
version = 1.05
min_version = 2025

;Campos opcionales:
;min_php = 8.2
require = 'OpenServBus, CSVimport'
;require_php = 'soap'
;compatible = 'Tickets'