name = 'OSBFuelImport'
description = 'OSBFuelImport'
version = 2.01
min_version = 2026

;Campos opcionales:
;min_php = 8.2
require = 'OpenServBus, CSVimport'
;require_php = 'soap'
;compatible = 'Tickets'